apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-node
  namespace: default
  labels:
    app: chrome-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome-node
  template:
    metadata:
      labels:
        app: chrome-node
    spec:
      containers:
        - name: chrome-node
          image: selenium/node-chrome:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub-service
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_NODE_MAX_SESSIONS
              value: "1"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=selenium-chrome-node,service.version=1.0"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: SE_NODE_GRID_URL
              value: "http://selenium-hub-service:4444"
          ports:
            - containerPort: 5555
              protocol: TCP
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /status
              port: 5555
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /status
              port: 5555
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
