apiVersion: v1
kind: Service
metadata:
  name: chrome-node-service
spec:
  selector:
    app: chrome-node-service
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
  type: NodePort
