apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-node
  labels:
    app: chrome-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome-node
  template:
    metadata:
      name: chrome-node
      labels:
        app: chrome-node
    spec:
      containers:
        - name: chrome-node
          image: balicamihai/chrome-node:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4444
              protocol: TCP
      restartPolicy: Always
      