apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-node
  namespace: default
  labels:
    app: chrome-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrome-node
  template:
    metadata:
      name: chrome-node
      labels:
        app: chrome-node
    spec:
      containers:
        - name: chrome-node
          image: selenium/node-chrome:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub-service
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_NODE_MAX_SESSIONS
              value: "2"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
          ports:
            - containerPort: 5555
              protocol: TCP
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
