apiVersion: v1
kind: Service
metadata:
  name: chrome-node-service
  namespace: default
spec:
  selector:
    app: chrome-node
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
