apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:

    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: "http://localhost:4318"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp]
