apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service
spec:
  selector:
    app: selenium-hub
  ports:
    - name: hub
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: events-publish
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: events-subscribe
      protocol: TCP
      port: 4443
      targetPort: 4443
  type: ClusterIP
  