apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcase-controller
  namespace: default
  labels:
    app: testcase-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcase-controller
  template:
    metadata:
      name: testcase-controller
      labels:
        app: testcase-controller
    spec:
      containers:
        - name: testcase-controller
          image: balicamihai/testcase-controller:amd64-4
          imagePullPolicy: IfNotPresent
          env:
            - name: USE_SELENIUM_GRID
              value: "true"
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: dockerhub-secret
